# Get all brands
GET http://localhost:9080/perfumes/api/brands

###

# Get single brand
GET http://localhost:9080/perfumes/api/brands/b7d9c9be-8dfd-426b-826f-4715f88c2f2e

###

# Create a new brand
PUT http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6
Content-Type: application/json

{
  "name": "New Brand Name",
  "description": "Description of the new brand"
}

###

# Update an existing brand
PATCH http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6
Content-Type: application/json

{
  "name": "Updated Brand Name",
  "description": "Updated description of the brand"
}

###

# Delete a brand
DELETE http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6

###

# Get all perfumes within a brand
GET http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6/perfumes

###

# Create a new perfume within a brand
PUT http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6/perfumes/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json

{
 "name": "Coco special",
  "description": "The main perfume of this brand",
  "releaseDate": "Tue Oct 08 04:45:08 CEST 2024",
  "price": 1200.0,
  "scentType": "FLORAL"
}

###

# Update an existing perfume within a brand
PATCH http://localhost:9080/perfumes/api/brands/b7d9c9be-8dfd-426b-826f-4715f88c2f2e/perfumes/3c6f1eb1-8069-44ab-988f-d7fed2b65d86
Content-Type: application/json

{
  "name": "Coco special",
  "price": 1800.0,
  "scentType": "FLORAL"
}

###

# Delete a perfume within a brand
DELETE http://localhost:9080/perfumes/api/brands/b7d9c9be-8dfd-426b-826f-4715f88c2f2e/perfumes/3c6f1eb1-8069-44ab-988f-d7fed2b65d86

###

# Get all perfumes across all brands
GET http://localhost:9080/perfumes/api/perfumes

###

# Get a single perfume by ID
GET http://localhost:9080/perfumes/api/perfumes/3c6f1eb1-8069-44ab-988f-d7fed2b65d86


########################################################################
# Get all characters. No credentials.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/characters

###

# Get all characters. Wrong credentials.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/characters
Authorization: Basic a2V2aW46d3JvbmdwYXNzd29yZA==

###


# Get all characters.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/characters
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get single character.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/characters/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get single character. Not existing, created later.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get single character portrait.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/characters/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0/portrait
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get single character portrait. Not existing, created later.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/portrait
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Create new character.

// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Sigrid",
  "background": "No one special.",
  "age": 18,
  "strength": 12,
  "constitution": 12,
  "charisma": 12,
  "health": 24,
  "profession": "f5875513-bf7b-4ae1-b8a5-5b70a1b90e76"
}

###

# Create character portait. Wrong credentials.

// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/portrait
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic a2V2aW46d3JvbmdwYXNzd29yZA==

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< simple-rpg/src/main/resources/pl/edu/pg/eti/kask/rpg/configuration/avatar/sigrid.png
--boundary--

###

# Create character portait.

// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87/portrait
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic a2V2aW46dXNlcnVzZXI=

--boundary
Content-Disposition: form-data; name="portrait"; filename="sigrid.png'

< simple-rpg/src/main/resources/pl/edu/pg/eti/kask/rpg/configuration/avatar/sigrid.png
--boundary--

###

# Create new character. Not existing profession.

// @no-cookie-jar
PUT http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Sigrid",
  "background": "No one special.",
  "age": 18,
  "strength": 12,
  "constitution": 12,
  "charisma": 12,
  "profession": "3bb5b0d5-7e22-466f-8c3f-be4baa3d3b8c"
}

###

# Update character. Wrong owner.

// @no-cookie-jar
PATCH http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic YWxpY2U6dXNlcnVzZXI=

{
  "name": "Sir Sigrid",
  "background": "Someone well known.",
  "age": 30
}

###

# Update character. Wrong credentials.

// @no-cookie-jar
PATCH http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46d3JvbmdwYXNzd29yZA==

{
  "name": "Sir Sigrid",
  "background": "Someone well known.",
  "age": 30
}

###

# Update character.

// @no-cookie-jar
PATCH http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Sir Sigrid",
  "background": "Someone well known.",
  "age": 30
}

###

# Delete character. Wrong owner.

// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Authorization: Basic YWxpY2U6dXNlcnVzZXI=

###

# Delete character. Wrong credentials.

// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Authorization: Basic a2V2aW46d3JvbmdwYXNzd29yZA==

###

# Delete character.

// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get all professions.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/professions
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get all profession characters.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/professions/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76/characters
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get all profession characters. Not existing.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/professions/d8b50a43-ed45-4441-9bcb-5db7782b47f6/characters
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get all user characters.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/users/81e1c2a9-7f57-439b-b53d-6db88b071e4e/characters
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get all user characters. Empty.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/characters
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get all user characters. Not existing.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/users/c07cab55-a56f-4d67-b351-175bb7a94b7a/characters
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get profession.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/professions/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Get non existing profession.

// @no-cookie-jar
GET http://localhost:9080/simple-rpg/api/professions/d8b50a43-ed45-4441-9bcb-5db7782b47f6
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Delete profesion. User.

// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/professions/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Authorization: Basic a2V2aW46dXNlcnVzZXI=

###

# Delete profesion. Admin.

// @no-cookie-jar
DELETE http://localhost:9080/simple-rpg/api/professions/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
