# kevin:useruser -> a2V2aW46dXNlcnVzZXI=
# admin:adminadmin -> YWRtaW46YWRtaW5hZG1pbg==
# alice:useruser -> YWxpY2U6dXNlcnVzZXI=

# Get all brands
# Permit all
// @no-cookie-jar
GET http://localhost:9080/perfumes/api/brands
Authorization: Basic a2V2aW46dXNlcnVzZXI=
###

# Get single brand
# Permit all
// @no-cookie-jar
GET http://localhost:9080/perfumes/api/brands/b7d9c9be-8dfd-426b-826f-4715f88c2f2e
Authorization: Basic a2V2aW46dXNlcnVzZXI=
###

# Create a new brand
# Permit admin
// @no-cookie-jar
PUT http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

{
  "name": "New Brand Name",
  "description": "Description of the new brand"
}

###

# Update an existing brand
# Permit admin
// @no-cookie-jar
PATCH http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

{
  "name": "Updated Brand Name 2",
  "description": "Updated description of the brand"
}

###

# Delete a brand
# Permit admin
// @no-cookie-jar
DELETE http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
###

# Get all perfumes within a brand
// @no-cookie-jar
GET http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6/perfumes
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

###

# Create a new perfume within a brand
// @no-cookie-jar
PUT http://localhost:9080/perfumes/api/brands/d8b50a43-ed45-4441-9bcb-5db7782b47f6/perfumes/3c6f1eb1-8069-44ab-988f-d7fed2b65d87
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

{
 "name": "Coco special",
  "description": "The main perfume of this brand",
  "releaseDate": "Tue Oct 08 04:45:08 CEST 2024",
  "price": 1200.0,
  "scentType": "FLORAL"
}

###

# Update an existing perfume within a brand
# alice perfume YWxpY2U6dXNlcnVzZXI=
// @no-cookie-jar
PATCH http://localhost:9080/perfumes/api/brands/b7d9c9be-8dfd-426b-826f-4715f88c2f2e/perfumes/3fa7d874-8a33-47d1-8a65-558c50a64d56
Content-Type: application/json
Authorization: Basic YWxpY2U6dXNlcnVzZXI=

{
  "name": "Coco Mademoiselle U",
  "price": 1800.0,
  "scentType": "FLORAL"
}

# Update an existing perfume within a brand
# kevin perfume a2V2aW46dXNlcnVzZXI=
// @no-cookie-jar
PATCH http://localhost:9080/perfumes/api/brands/a1d6a00b-4d4f-4dbd-9b8b-08b4c8b68b6b/perfumes/ed50cbf7-67e8-4a1b-9e4d-627d6a587b36
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Sauvage U",
  "price": 1200.0,
  "scentType": "SPICY"
}

###

# Delete a perfume within a brand
// @no-cookie-jar
DELETE http://localhost:9080/perfumes/api/brands/b7d9c9be-8dfd-426b-826f-4715f88c2f2e/perfumes/3fa7d874-8a33-47d1-8a65-558c50a64d56

###

# Get all perfumes across all brands
// @no-cookie-jar
GET http://localhost:9080/perfumes/api/perfumes
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

###

# Get a single perfume by ID
// @no-cookie-jar
GET http://localhost:9080/perfumes/api/perfumes/3fa7d874-8a33-47d1-8a65-558c50a64d56

###

# Get all users
// @no-cookie-jar
GET http://localhost:9080/perfumes/api/users
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

###

# Create a new user
// @no-cookie-jar
PUT http://localhost:9080/perfumes/api/users/3c6f1eb1-8069-44ab-988f-d7fed2b65d22
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

{
    "login": "john_doe",
    "name": "John",
    "surname": "Doe",
    "email": "john.doe@example.com",
    "password": "securepassword123",
    "birthDate": "1980-01-01"
}